runtime: custom
env: flex
env_variables:
  SPRING_PROFILES_ACTIVE: "gcp,mysql"
handlers:
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301
resources:
  cpu: 2
  memory_gb: 2
  disk_size_gb: 10
  volumes:
    - name: ramdisk1
      volume_type: tmpfs
      size_gb: 0.5
manual_scaling:
  instances: 1
#automatic_scaling:
#  min_num_instances: 1
#  max_num_instances: 8
#  cool_down_period_sec: 120
#  cpu_utilization:
#    target_utilization: 0.7
liveness_check:
  path: "/liveness"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  initial_delay_sec: 300
readiness_check:
  path: "/readiness"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 1200
