package com.socatel.utils.enums;

public enum  HistoryTypeEnum {
    CREATED_ACCOUNT, CREATED_ORGANISATION, JOINED_ORGANISATION, CREATED_GROUP, POSTED_GROUP,
    SUBSCRIBED_GROUP, UNSUBSCRIBED_GROUP, VIEWED_GROUP, DEACTIVATE_ACCOUNT,
    DELETE_ACCOUNT, RESTORE_ACCOUNT, PASSWORD_RESET, EDIT_AGE_RANGE, EDIT_GENDER,
    EDIT_POI, EDIT_SKILLS, EDIT_USERNAME, EDIT_PROFILE, EDIT_DESCRIPTION,
    EDIT_LOCALITY, EDIT_FIRST_LANGUAGE, EDIT_SECOND_LANGUAGE, EDIT_AVATAR, EDIT_ORGANISATION,
    EDIT_NOTIFICATIONS, EDIT_EMAIL, SEARCH_TOPIC, MESSAGE_USER, SEARCH_SERVICE
}
